version: "3.9"

services:
  api:
    build: ./backend
    container_name: ai_immigration_api
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
      - ./backend/conversation_logs.db:/app/conversation_logs.db
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
      - QDRANT_URL=http://qdrant:6333
      - HF_TOKEN=${HF_TOKEN}
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - ai_immigration_network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: ai_immigration_qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__STORAGE__WAL_DIR=/qdrant/storage
    restart: unless-stopped
    networks:
      - ai_immigration_network

networks:
  ai_immigration_network:
    driver: bridge

volumes:
  qdrant_data:
  models_data: 